### ISSUE TITLE
DB 인스턴스 분리

### ISSUE THREAD

**Issue by shinkeonkim** [today-they-learned/ttl_api#103]
RDS를 쓸지, 다른 플랫폼을 쓸지 검토해야함.

**Comment by Jihyun-Choi** [comment]
1. DB 인스턴스 분리를 하고자하는 이유는 무엇인가요?   (혹시나 터져서 DB가 날아갈까봐...?)
2. RDS를 쓸지 다른 플랫폼을 쓸지 검토함은, 어떤 부분에서 고민이 들었기에 검토하고자하는지 궁금합니다.

**Comment by shinkeonkim** [comment]
1. 네 맞습니다. 그리고, 서버 운영을 동적으로하기 위함이에요. 현재는 EC2를 하나로 쓰고 있는데, 디비를 따로 분리해둔 다면, EC2를 여러개로 사용할 수 있습니다. Web server를 여러개 쓰면서 로드 밸런서를 붙일까 해여
2. RDS가 너무 비싸요 ㅠ
